# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4np28fSVnjTICO3ukqoPFof5Ir7TRK7
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard.py
# 
# import streamlit as st
# import pandas as pd
# import os
# import matplotlib.pyplot as plt
# 
# st.set_page_config(
#     page_title="E-Commerce Dashboard",
#     layout="wide"
# )
# 
# st.title("📊 E-Commerce Public Dataset")
# st.subheader("Dashboard Analisis Data Penjualan")
# 
# # =========================
# # LOAD DATA
# # =========================
# 
# base_path = "/content/data/E-Commerce Public Dataset"
# 
# orders_df = pd.read_csv(
#     os.path.join(base_path, "orders_dataset.csv")
# )
# 
# order_items_df = pd.read_csv(
#     os.path.join(base_path, "order_items_dataset.csv")
# )
# 
# products_df = pd.read_csv(
#     os.path.join(base_path, "products_dataset.csv")
# )
# 
# category_translation_df = pd.read_csv(
#     os.path.join(base_path, "product_category_name_translation.csv")
# )
# 
# # Mengubah kolom tanggal
# orders_df["order_purchase_timestamp"] = pd.to_datetime(
#     orders_df["order_purchase_timestamp"]
# )
# 
# # =========================
# # PERTANYAAN 1
# # =========================
# 
# st.header("1. Perkembangan Pesanan dan Penjualan per Bulan")
# 
# sales_df = pd.merge(
#     orders_df[["order_id", "order_purchase_timestamp"]],
#     order_items_df[["order_id", "price"]],
#     on="order_id",
#     how="inner"
# )
# 
# sales_df["month"] = sales_df[
#     "order_purchase_timestamp"
# ].dt.to_period("M").astype(str)
# 
# monthly_sales = sales_df.groupby("month").agg(
#     total_orders=("order_id", "nunique"),
#     total_sales=("price", "sum")
# ).reset_index()
# 
# fig1, ax1 = plt.subplots(figsize=(12, 5))
# 
# ax1.plot(
#     monthly_sales["month"],
#     monthly_sales["total_orders"],
#     marker="o"
# )
# 
# ax1.set_title("Perkembangan Jumlah Pesanan per Bulan")
# ax1.set_xlabel("Bulan")
# ax1.set_ylabel("Jumlah Pesanan")
# ax1.tick_params(axis="x", rotation=45)
# 
# st.pyplot(fig1)
# 
# fig2, ax2 = plt.subplots(figsize=(12, 5))
# 
# ax2.plot(
#     monthly_sales["month"],
#     monthly_sales["total_sales"],
#     marker="o"
# )
# 
# ax2.set_title("Perkembangan Total Nilai Penjualan per Bulan")
# ax2.set_xlabel("Bulan")
# ax2.set_ylabel("Total Penjualan")
# ax2.tick_params(axis="x", rotation=45)
# 
# st.pyplot(fig2)
# 
# # =========================
# # PERTANYAAN 2
# # =========================
# 
# st.header("2. Kategori Produk dengan Pesanan dan Penjualan Tertinggi")
# 
# category_sales = pd.merge(
#     order_items_df[["order_id", "product_id", "price"]],
#     products_df[["product_id", "product_category_name"]],
#     on="product_id",
#     how="left"
# )
# 
# category_sales = pd.merge(
#     category_sales,
#     category_translation_df,
#     on="product_category_name",
#     how="left"
# )
# 
# category_sales["category"] = category_sales[
#     "product_category_name_english"
# ].fillna("unknown")
# 
# category_summary = category_sales.groupby(
#     "category"
# ).agg(
#     total_orders=("order_id", "nunique"),
#     total_sales=("price", "sum")
# ).reset_index()
# 
# # 10 kategori dengan jumlah pesanan tertinggi
# top_orders = category_summary.sort_values(
#     "total_orders",
#     ascending=False
# ).head(10)
# 
# fig3, ax3 = plt.subplots(figsize=(12, 5))
# 
# ax3.bar(
#     top_orders["category"],
#     top_orders["total_orders"]
# )
# 
# ax3.set_title("10 Kategori dengan Jumlah Pesanan Tertinggi")
# ax3.set_xlabel("Kategori Produk")
# ax3.set_ylabel("Jumlah Pesanan")
# ax3.tick_params(axis="x", rotation=45)
# 
# st.pyplot(fig3)
# 
# # 10 kategori dengan total penjualan tertinggi
# top_sales = category_summary.sort_values(
#     "total_sales",
#     ascending=False
# ).head(10)
# 
# fig4, ax4 = plt.subplots(figsize=(12, 5))
# 
# ax4.bar(
#     top_sales["category"],
#     top_sales["total_sales"]
# )
# 
# ax4.set_title("10 Kategori dengan Total Nilai Penjualan Tertinggi")
# ax4.set_xlabel("Kategori Produk")
# ax4.set_ylabel("Total Penjualan")
# ax4.tick_params(axis="x", rotation=45)
# 
# st.pyplot(fig4)
# 
# st.header("Kesimpulan")
# 
# st.write(
#     "Kategori dengan jumlah pesanan tertinggi adalah "
#     f"**{top_orders.iloc[0]['category']}**, sedangkan kategori "
#     "dengan total nilai penjualan tertinggi adalah "
#     f"**{top_sales.iloc[0]['category']}**."
# )

import zipfile
import os

zip_path = '/content/E-commerce-public-dataset.zip'
extract_path = '/content/data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset berhasil diekstrak.")

os.listdir('/content/data')

!streamlit run dashboard.py &>/content/logs.txt &

!npx localtunnel --port 8501
